services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always

  bot:
    build:
      context: ./bot
    depends_on:
      - redis
    ports:
      - '80:80'
    environment:
      - BOT_TOKEN=7484139398:AAHwFUGUDOSo8iw3E7W27lbVeCCD581xb7M
      - SUPPORT_CONTACT=https://t.me/kostantina_1
      - ADMIN_ID=-1002203096131
      - LINK_DOMAIN=https://t.me/CashCygnetBot_bot
      - POSTBACK_URL=http://185.190.250.47/69dd446/postback?
      - WD_BOT_TOKEN=7286021357:AAHQuuPVfev4b-WEpRuAVpRqfFj5HNGmAwE
    restart: always